Vagrant.configure("2") do |config|
  # config.vm.box = "ubuntu/xenial64"
  config.vm.box = "ubuntu/trusty64"

  # config.vm.network "forwarded_port", guest: 3000, host: 3000
  # config.vm.network "forwarded_port", guest: 9090, host: 9000
  # config.vm.hostname = "vm1"
  # config.vm.network "private_network", ip: "192.168.33.10"

  # host, gest
  # config.vm.synced_folder "synced_folder", "/synced_folder"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    # vb.gui = true

    # Customize the amount of memory on the VM:
    vb.memory = "2048"
  end


  config.vm.provision "shell" do |s|
    s.inline = "timedatectl set-timezone Asia/Tokyo"
    s.inline = "apt-get update"
  end

  config.vm.provision "shell", path: "provision/git.sh"
  config.vm.provision "shell", path: "provision/node.sh"

end
