Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.network "forwarded_port", guest: 9000, host: 9000

  # host, gest
  # config.vm.synced_folder "synced_folder", "/synced_folder"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    # vb.gui = true

    # Customize the amount of memory and CPU on the VM:
    vb.cpus = 2
    vb.memory = "4096"
  end

  config.vm.provision "shell" do |s|
    s.inline = "timedatectl set-timezone Asia/Tokyo"
    s.inline = "sudo apt-get update"
    s.inline = "sudo apt-get install -y unzip"
    s.inline = "sudo apt-get install -y memcached"
  end

  config.vm.provision "shell", path: "provision/useradd.sh"
  config.vm.provision "shell", path: "provision/mongodb.sh"
  config.vm.provision "shell", path: "provision/mysql.sh"
  config.vm.provision "shell", path: "provision/git.sh"
  config.vm.provision "shell", path: "provision/java.sh"
  config.vm.provision "shell", path: "provision/playframework.sh"
end
