Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  # GestOs Synchronized directory from hostOS (host, gest)
  config.vm.synced_folder "sync_folder", "/sync_folder"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    # vb.gui = true

    # Customize the amount of memory and CPU on the VM:
    vb.cpus = 2
    vb.memory = "2048"
  end



  config.vm.provision "shell" do |s|
    s.inline = "timedatectl set-timezone Asia/Tokyo"
    s.inline = "sudo apt update"
    # s.inline = "sudo apt-get install -y unzip zip"
  end

  config.vm.provision "file", source: "config/.bash_profile", destination: "/home/ubuntu/.bash_profile"

  # config.vm.provision "shell", path: "provision/user_add.sh"
  config.vm.provision "shell", path: "provision/git.sh"
  config.vm.provision "shell", path: "provision/python.sh"

end
