Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 2
    vb.memory = "2048"
  end

  config.vm.provision "shell" do |s|
    s.inline = "timedatectl set-timezone Asia/Tokyo"
    s.inline = "sudo apt update"
    s.inline = "sudo apt install -y unzip zip"
  end

  config.vm.provision "shell", path: "provision/useradd.sh"
  config.vm.provision "shell", path: "provision/kotlin.sh"

end
